title: "Senior Research Project"
description: "Comparing WAVE and AXE DevTools for accessibility testing"
theme: jekyll-theme-merlot
author: "Jhelani Crawford"
github:
  is_project_page: true
  repository_url: https://github.com/2e-zz/senior-research-project
